Tarea1M1C1
changligia/Modulo1Clase1_JAVA pull request #1
Opened 2022-09-28 00:50 UTC by changligia

PR tarea1m1c1

2022-09-28 00:53 UTC, calvarioTeacher31 requested changes

2022-09-28 00:53 UTC, calvarioTeacher31 commented on src/Ejercicio1M1C1.java
> +    }
espacio luego de la línea 22

2022-09-28 00:53 UTC, calvarioTeacher31 commented on src/Ejercicio1M1C1.java
> +        var entero1 = scanner.nextInt();
se pedía leer doubles no enteros

2022-09-28 00:53 UTC, calvarioTeacher31 commented on src/Ejercicio3M1C1.java
> +        scanner.close();
el scanner se cierra después de la última lectura en este caso después de la línea 9

2022-09-28 00:53 UTC, calvarioTeacher31 commented on src/Ejercicio3M1C1.java
> +        if (numero % 2 == 0){
if/else redundante puedes retornar de frente numero %2 == 0 ya que esa operación devuelve un boolean

2022-09-28 00:53 UTC, calvarioTeacher31 commented on src/Ejercicio4M1C1.java
> +        var a = 2;
estoy casi seguro que pido todo leer por teclado aquí has harcodeado todos con el valor de 2

2022-09-28 00:53 UTC, calvarioTeacher31 commented on src/Ejercicio4M1C1.java
> +        Suma(a, b, c, d);
métodos comienza con minúscula

2022-09-28 00:53 UTC, calvarioTeacher31 commented on src/Ejercicio4M1C1.java
> +    static void División (int w, int x, int y, int z){
métodos no deben tener tildes

2022-09-28 00:54 UTC, calvarioTeacher31 commented on src/Ejercicio4M1C1.java
> +    static void División (int w, int x, int y, int z){
aclaración pra todos los métodos de esta clase no solo para División

2022-09-28 00:54 UTC, calvarioTeacher31 commented on src/Ejercicio4M1C1.java
> +        Suma(a, b, c, d);
aplica para todos los métodos de esta clase

2022-09-28 01:06 UTC, calvarioTeacher31 requested changes

2022-09-28 01:06 UTC, calvarioTeacher31 commented on src/Ejercicio2M1C1.java
> +    }
espacio línea 22

2022-09-28 01:06 UTC, calvarioTeacher31 commented on src/Ejercicio3M1C1.java
> +        }else{
el else{ solo denota que el save actions no está funcionando o no lo has instalado ya que no se está formateando correctamente el código

2022-09-28 02:14 UTC, changligia commented on src/Ejercicio3M1C1.java
> +        }else{
listooo

2022-09-28 02:33 UTC, calvarioTeacher31 requested changes

2022-09-28 02:33 UTC, calvarioTeacher31 commented on src/Ejercicio4M1C1.java
> +    static void Suma(int w, int x, int y, int z) {
los métodos comienza con minúscula... suma, resta, multiplicación solo las Clases comienza con mayúsucla

2022-09-28 14:28 UTC, changligia commented on src/Ejercicio4M1C1.java
> +    static void Suma(int w, int x, int y, int z) {
listo

2022-09-28 14:36 UTC, calvarioTeacher31 approved these changes

2022-10-05 17:07 UTC, changligia commented
Tarea1M1M1 completada

2022-10-05 17:07 UTC, merged